version: "3"

services:
  app:
    build:
      context: ./app
    command: node /home/node/index.js
    environment:
      HOST_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - "${PWD}/app/server.js:/home/node/index.js"
  
  proxied-app:
    extends: app
    depends_on:
      - proxy
    environment:
      NODE_EXTRA_CA_CERTS: /home/node/certs/localhost-CA.crt
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # Using this to get around error "reason: Hostname/IP does not match certificate's altnames: Host: <HOST>. is not in the cert's altnames: DNS:localhost
    networks:
      - outgoing
    volumes:
      - "${PWD}/certs:/home/node/certs"
  
  proxy:
    build:
      context: ./proxy
    command: node /home/node/proxy/server.js
    command: node --inspect=0.0.0.0:9229 /home/node/proxy/server.js
    environment:
      CRT: /home/node/certs/localhost.crt
      KEY: /home/node/certs/localhost.key
      NODE_EXTRA_CA_CERTS: /home/node/certs/localhost-CA.crt
    networks:
      outgoing:
        aliases: # alias this Server by these domains
          - api.icndb.com
          - jsonplaceholder.typicode.com
          - rickandmortyapi.com
    ports:
      - 9229:9229
    volumes:
      - "${PWD}/certs:/home/node/certs"
      - "${PWD}/proxy:/home/node/proxy"

networks:
  outgoing:
    driver: bridge
