services:
  example-app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    container_name: example-app
    environment:
      # SERVER_PORT: 3000 # make Server listen on a different port
      TZ: America/Los_Angeles
    ports:
      # Map Local port to the Container's exposed port
      - "3000:80"
    user: "${CURR_UID}:${CURR_GID}"
    # volumes:
    #   - type: bind
    #     source: "${PWD}/.app_data"
    #     target: "/app_data"
    #   - type: bind
    #     source: "${PWD}/certs"
    #     target: "/app_certs"
  
  example-app-dev:
    extends: example-app # allows for just changing key pieces of data for development
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: example-app-dev # if this changes, update `repo-funcs.sh`
    environment:
      NODE_ENV: development
    ports:
      # inspector
      - "9229:9229"
    volumes:
      # Map shell files over, so they're maintained between sessions
      # - "${PWD}/.docker/.vimrc:/home/node/.vimrc"
      # - "${PWD}/.docker/.zshrc:/home/node/.zshrc"
      - "${PWD}/.ignore:/home/node/dev" # allows for .zsh_history to be written
      # Map the current directory over for development
      - "${PWD}:/home/node/app"
  
  node20-base-image:
    build:
      context: ./
      dockerfile: .docker/base.Dockerfile
    image: theonewhoknocks/dev-base:node20
